name: Backend CI on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:
  check-paths:
    uses: ./.github/workflows/path-checker.yml
    with:
      base_ref: ${{ github.event.pull_request.base.sha }}
      head_ref: ${{ github.event.pull_request.head.sha }}
      paths: 'backend/'

  build-and-analyze:
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.changes_detected == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Ensure this version is correct for your project
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Generate coverage report
        run: mvn clean verify -Pcoverage --batch-mode

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
        run: mvn sonar:sonar -Dsonar.java.binaries=target/classes -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml --batch-mode
