name: Backend CI on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true


jobs:
  check-paths:
    uses: ./.github/workflows/path-checker.yml
    with:
      base_ref: ${{ github.event.pull_request.base.sha }}
      head_ref: ${{ github.event.pull_request.head.sha }}
      paths: 'backend/'

  setup:
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.changes_detected }}
    uses: ./.github/workflows/setup-jdk-and-checkout.yml
    with:
      java-version: '21'
      distribution: 'temurin'

  build-and-analyze:
    needs: [setup]
    if: ${{ needs.setup.outputs.cache-key }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: ${{ needs.setup.outputs.cache-key }}

      - name: Build and Generate coverage report
        run: mvn clean verify -Pcoverage --batch-mode

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar
