name: Common Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  labeler:
    name: Label PRs
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
