name: Path Changes Checker

on:
  workflow_call:
    inputs:
      base_ref:
        required: true
        type: string
      head_ref:
        required: true
        type: string
      paths:
        required: true
        type: string
        description: "Paths to check, separated by a space"

jobs:
  path-check:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.changes.outputs.changes_detected }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Check for changes in specified paths
        id: changes
        run: |
          echo "Checking for changes in the following paths: ${{ github.event.inputs.paths }}"
          IFS=' ' read -r -a paths_array <<< "${{ github.event.inputs.paths }}"
          CHANGES_DETECTED=false
          for path in "${paths_array[@]}"
          do
            if git diff --name-only ${{ github.event.inputs.base_ref }}...${{ github.event.inputs.head_ref }} | grep -E "^(${path})"
            then
              CHANGES_DETECTED=true
              break
            fi
          done
          echo "::set-output name=changes_detected::$CHANGES_DETECTED"
