name: Backend CI on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop


jobs:
  labeler:
    name: Label PRs
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

  check-paths:
    uses: ./.github/workflows/path-checker.yml
    with:
      base_ref: ${{ github.event.pull_request.base.sha }}
      head_ref: ${{ github.event.pull_request.head.sha }}
      paths: 'backend/**/*'

  backend-code-quality:
    name: Backend Code Quality
    needs: check-paths
    if: ${{ needs.check-paths.outputs.changes_detected == 'true' }}
    uses: ./.github/workflows/code_quality.yml
    secrets: inherit
