name: Backend CI on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop


jobs:
  labeler:
    name: Label PRs
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

  backend-code-quality:
    name: Backend Code Quality
    uses: ./.github/workflows/code_quality.yml
    secrets: inherit
